version: '2'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name:  zipkin
#    ports:
#      - "9411:9411"
    network_mode:  "host"
    environment: 
      spring.profiles.active: "default"
      server.port: "9411" 
#      spring.cloud.config.uri: "http://localhost:8888" 
#      eureka.client.enabled: "true"
#      eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
#      spring.boot.admin.url: http://localhost:8181/sba
      TZ: Asia/Taipei
      STORAGE_TYPE: mem
        
      