version: '3.1'
services:
  grafana:
    image: grafana/grafana
    container_name:  grafana
#    ports:
#    - 3000:3000
    network_mode:  "host"
    volumes:
    - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=monitoring
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    
  prometheus:
    image: prom/prometheus
    container_name:  prometheus
#    ports:
#    - 9090:9090
    network_mode:  "host"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
volumes:
  prometheus_data: {}
  grafana_data: {}